/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.View;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.MenuBar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Hexters
 */
public class MainFrameView extends javax.swing.JFrame implements ActionListener {

    private final JPanel 
            authView,
            adminView,
            userView;
    private final CardLayout cardLayout = new CardLayout();
    
    public final JMenu file;
    public final JMenu master;
    public final JMenu transaksi;
    public final JMenu window;
    public final JMenuItem exit;
    public final JMenuItem about;
    
    public JMenuBar menuBar;
    
    /**
     * Creates new form AdminFrameView
     */
    public MainFrameView() {
        initComponents();
        
        this.setTitle("UAS - Halaman Login");
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        panelutama.setLayout(cardLayout);
        
        authView = new AuthPanelView(this);
        adminView = new AdminView(this);
        userView = new UserView(this);
        
        panelutama.add(authView, "authView");
        panelutama.add(adminView, "adminView");
        panelutama.add(userView, "userView");
        
        
        menuBar = new JMenuBar();
            
        file = new JMenu("File");
        window = new JMenu("Window");
        master = new JMenu("Master");
        transaksi = new JMenu("Transaksi");

        exit = new JMenuItem("Exit");
        about = new JMenuItem("About");

        file.add(exit);
        window.add(about);
        
        menuBar.add(file);
        menuBar.add(window);
       
        this.setJMenuBar(menuBar);
        
        exit.addActionListener(this);
        
    }
    
    public void showPanel(String panelIdentifier) {
        System.out.println(panelIdentifier);
        CardLayout cardLyout = (CardLayout) panelutama.getLayout();
        cardLyout.show(panelutama, panelIdentifier);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        getContentPane().add(panelutama);

        setSize(new java.awt.Dimension(506, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelutama;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println(e.getSource());
        if(e.getSource() == exit) {
            System.exit(0);
        }
    }

}
